### ISSUE TITLE
Requirement model in Enterprise Architect format

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-requirements-models#14]
[requirements.feap.zip](https://github.com/metanorma/metanorma-requirements-models/files/5807278/requirements.feap.zip)

**Comment by ronaldtse** [comment]
@VasBu this file doesn't seem to work for me. Can you help upload an EAP or EAPX file, and also make two exports: XMI 2.4.2 and XMI 2.5.1?

@w00lf please watch here for the corresponding model.

We need to implement parsing of the XMI files such that we can do:
* (Enterprise Architect: EAP -> XMI) -> LutaML parses the exported XMI -> in LutaML we can navigate the UML tree

**Comment by VasBu** [comment]
[Requirements.zip](https://github.com/metanorma/metanorma-requirements-models/files/5807930/Requirements.zip)
@ronaldtse , Please find EAPX file version. I hope this will work for you.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by VasBu** [comment]
[Requirements - XMI-242-251.zip](https://github.com/metanorma/metanorma-requirements-models/files/5817157/Requirements.-.XMI-242-251.zip)

Dear @ronaldtse ,
Sorry for being a bit slow. Please find the the attachment that includes XML files from the **Requirements** model in XMI 2.4.2 and XMI 2.5.1 format.

Ping @w00lf
