### ISSUE TITLE
OGC ModSpec (OGC 08-131r3) UML models in EA and XMI 2.4.2/2.5.1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-requirements-models#15]
OGC ModSpec (OGC 08-131r3) provides Figure C.1 which lists out a set of UML models.

This task is to encode these models in Enterprise Architect and export them to XML 2.4.2/2.5.1.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/11865/102055154-6094ab00-3e25-11eb-86d6-6a53cfb8818f.png">

@VasBu can you help with this? Thanks!

**Comment by VasBu** [comment]
Hey @ronaldtse ,

Just to clarify the task:

- I need to create the diagram under the **figure C.1** in EA;
- Create diagram/model to be exported into the following formats:  XML 2.4.2 and XML 2.5.1;

Would you please confirm that I understood the things correctly about this assignment?

**Comment by ronaldtse** [comment]
The diagram under EA can be packaged under any name, e.g. "ModSpec". The point is to encode the diagram provided above Figure C.1.

> Create diagram/model to be exported into the following formats: XML 2.4.2 and XML 2.5.1;
(seems that macOS autocorrects "XMI" to "XML"... ugh)

In Enterprise Architect there is the option to "publish" XMI 2.4.2 and XMI 2.5.1.

XMI 2.4.2 is called "Normative XMI" in EA
<img width="158" alt="Screen Shot 2021-01-15 at 9 05 18 AM" src="https://user-images.githubusercontent.com/11865/104667323-ccae4b80-5710-11eb-9f08-f417fb5c2c3c.png">

Both XMI 2.4.2 and XMI 2.5.1 can be found in the "Other Formats" popup:
<img width="517" alt="Screen Shot 2021-01-15 at 9 04 25 AM" src="https://user-images.githubusercontent.com/11865/104667275-ad172300-5710-11eb-8ab7-b86e18695665.png">

**Comment by VasBu** [comment]
Dear @ronaldtse , please find the attachment that includes EAPX file and the XMI exports.
[ModSpec.zip](https://github.com/metanorma/metanorma-requirements-models/files/5826964/ModSpec.zip)

**Comment by ronaldtse** [comment]
Thank you @VasBu !
